services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adir12345
      - POSTGRES_DB=auctions
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=adir12345
    volumes:
      - mongodata:/var/lib/mongodb/data
volumes:
  pgdata:
  mongodata:
